PACKAGES="tmux python stow vim emacs ctags cscope global curl aria2 tig ranger the_silver_searcher autojump"
DEV_PACKAGES="gcc-c++ clang zeal"
MANAGES="fabric ansible"
XPACKAGES="gvim i3 termite rofi compton"
PIP="pip"
PYTHON_PACKAGES="virtualenv"
